### ISSUE TITLE
feedback with draft of pattern

### ISSUE THREAD

**Issue by ljbennett62** [IBM/protect-webapp-using-runtime-container-security#15]
Hi  Shikha, I have reviewed your pattern and have the following feedback: (fyi Tracy)

- it would have been better to go the route of using NeuVector on OpenShift given our strategic focus there and driving more RH usage
-Please add a link to the reference you made wrt: DVWA (Damn Vulnerable Web Application)
- It would be good to reference the key lines in teh deployment.yaml file
- You should give more details when you make this stmt: `Please ensure that you have activated NeuVector by providing the proper License code before proceeding further.` Where do they go to get this.
- This stmt is confusing: `The vulnerable application exposes an API for password change: http://[public-ip-of-cluster]:32425/vulnerabilities/csrf/?password_new=password&password_conf=password&Change=Change`.  Which vulnerable application, and did you mean to make the end of the stmt a link that the reader could go to? Maybe show in the code where this application vulnerability is specifically.
- In your stmt: `The sample application provides the functionality to upload the file.` - where is this and you say `the file` - perhaps restate `a malicious file such as <give example> `. You also say `take actions accordingly` - what specific actions will it take?
- In teh section about Cross Site Scripting - you note `there are vulnerable APIs using which....` - can you give specific examples? BTW - when you show the information around sensor name, pattern name, etc - are these standard names - or would someone use different names (e.g. sensor.xss.get) - and if so what advice do we have for naming conventions
- with Sensitive Data exposure - are we supposed to do anything?
- 
- 
-

**Comment by maheshwarishikha** [comment]
@ljbennett62 Many thanks Laura for reviewing the code pattern. We have incorporated your feedback and merged the PR too. Hope it is good for publishing now. Thanks.

**Comment by ljbennett62** [comment]
@maheshwarishikha - per our conversation - I am fine with the updates you made. I have set up a call tomorrow with Tracy and Manjula to close on the last two issues.

**Comment by maheshwarishikha** [comment]
Thanks!
